#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_Parser
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDTransformacionInformacion")]
	public partial class DCCamaraComercioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttbCamposContextuales_CamaraComercio(tbCamposContextuales_CamaraComercio instance);
    partial void UpdatetbCamposContextuales_CamaraComercio(tbCamposContextuales_CamaraComercio instance);
    partial void DeletetbCamposContextuales_CamaraComercio(tbCamposContextuales_CamaraComercio instance);
    partial void InserttbEncabezados_CamaraComercio(tbEncabezados_CamaraComercio instance);
    partial void UpdatetbEncabezados_CamaraComercio(tbEncabezados_CamaraComercio instance);
    partial void DeletetbEncabezados_CamaraComercio(tbEncabezados_CamaraComercio instance);
    partial void InserttbPalabrasClaves_CamaraComercio(tbPalabrasClaves_CamaraComercio instance);
    partial void UpdatetbPalabrasClaves_CamaraComercio(tbPalabrasClaves_CamaraComercio instance);
    partial void DeletetbPalabrasClaves_CamaraComercio(tbPalabrasClaves_CamaraComercio instance);
    partial void InserttbParametros(tbParametros instance);
    partial void UpdatetbParametros(tbParametros instance);
    partial void DeletetbParametros(tbParametros instance);
    #endregion
		
		public DCCamaraComercioDataContext() : 
				base(global::CC_Parser.Properties.Settings.Default.BDTransformacionInformacionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCCamaraComercioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCCamaraComercioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCCamaraComercioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCCamaraComercioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbCamposContextuales_CamaraComercio> tbCamposContextuales_CamaraComercio
		{
			get
			{
				return this.GetTable<tbCamposContextuales_CamaraComercio>();
			}
		}
		
		public System.Data.Linq.Table<tbEncabezados_CamaraComercio> tbEncabezados_CamaraComercio
		{
			get
			{
				return this.GetTable<tbEncabezados_CamaraComercio>();
			}
		}
		
		public System.Data.Linq.Table<tbPalabrasClaves_CamaraComercio> tbPalabrasClaves_CamaraComercio
		{
			get
			{
				return this.GetTable<tbPalabrasClaves_CamaraComercio>();
			}
		}
		
		public System.Data.Linq.Table<tbParametros> tbParametros
		{
			get
			{
				return this.GetTable<tbParametros>();
			}
		}
		
		public System.Data.Linq.Table<tbSedes_CamaraComercio> tbSedes_CamaraComercio
		{
			get
			{
				return this.GetTable<tbSedes_CamaraComercio>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarEncabezados_CamaraComercio")]
		public ISingleResult<spConsultarEncabezados_CamaraComercioResult> spConsultarEncabezados_CamaraComercio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="VarChar(200)")] string ciudad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ciudad);
			return ((ISingleResult<spConsultarEncabezados_CamaraComercioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarLista_CamaraComercio")]
		public ISingleResult<spConsultarLista_CamaraComercioResult> spConsultarLista_CamaraComercio()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarLista_CamaraComercioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarRegion_CamaraComercio")]
		public ISingleResult<spConsultarRegion_CamaraComercioResult> spConsultarRegion_CamaraComercio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Consecutivo", DbType="Int")] System.Nullable<int> consecutivo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), consecutivo);
			return ((ISingleResult<spConsultarRegion_CamaraComercioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarCamposContextuales_CamaraComercio")]
		public ISingleResult<spConsultarCamposContextuales_CamaraComercioResult> spConsultarCamposContextuales_CamaraComercio()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarCamposContextuales_CamaraComercioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarPalabrasClaves_CamaraComercio")]
		public ISingleResult<spConsultarPalabrasClaves_CamaraComercioResult> spConsultarPalabrasClaves_CamaraComercio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CampoContextual", DbType="Int")] System.Nullable<int> campoContextual)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), campoContextual);
			return ((ISingleResult<spConsultarPalabrasClaves_CamaraComercioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarEncabezadosGeneral_CamaraComercio")]
		public ISingleResult<spConsultarEncabezadosGeneral_CamaraComercioResult> spConsultarEncabezadosGeneral_CamaraComercio()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarEncabezadosGeneral_CamaraComercioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCamposContextuales_CamaraComercio")]
	public partial class tbCamposContextuales_CamaraComercio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONSECUTIVO;
		
		private string _FIELD;
		
		private System.Nullable<int> _TOTAL_WORDS_LEFT;
		
		private System.Nullable<int> _TOTAL_WORDS_RIGTH;
		
		private EntitySet<tbPalabrasClaves_CamaraComercio> _tbPalabrasClaves_CamaraComercio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONSECUTIVOChanging(int value);
    partial void OnCONSECUTIVOChanged();
    partial void OnFIELDChanging(string value);
    partial void OnFIELDChanged();
    partial void OnTOTAL_WORDS_LEFTChanging(System.Nullable<int> value);
    partial void OnTOTAL_WORDS_LEFTChanged();
    partial void OnTOTAL_WORDS_RIGTHChanging(System.Nullable<int> value);
    partial void OnTOTAL_WORDS_RIGTHChanged();
    #endregion
		
		public tbCamposContextuales_CamaraComercio()
		{
			this._tbPalabrasClaves_CamaraComercio = new EntitySet<tbPalabrasClaves_CamaraComercio>(new Action<tbPalabrasClaves_CamaraComercio>(this.attach_tbPalabrasClaves_CamaraComercio), new Action<tbPalabrasClaves_CamaraComercio>(this.detach_tbPalabrasClaves_CamaraComercio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this.OnCONSECUTIVOChanging(value);
					this.SendPropertyChanging();
					this._CONSECUTIVO = value;
					this.SendPropertyChanged("CONSECUTIVO");
					this.OnCONSECUTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FIELD
		{
			get
			{
				return this._FIELD;
			}
			set
			{
				if ((this._FIELD != value))
				{
					this.OnFIELDChanging(value);
					this.SendPropertyChanging();
					this._FIELD = value;
					this.SendPropertyChanged("FIELD");
					this.OnFIELDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_WORDS_LEFT", DbType="Int")]
		public System.Nullable<int> TOTAL_WORDS_LEFT
		{
			get
			{
				return this._TOTAL_WORDS_LEFT;
			}
			set
			{
				if ((this._TOTAL_WORDS_LEFT != value))
				{
					this.OnTOTAL_WORDS_LEFTChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_WORDS_LEFT = value;
					this.SendPropertyChanged("TOTAL_WORDS_LEFT");
					this.OnTOTAL_WORDS_LEFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_WORDS_RIGTH", DbType="Int")]
		public System.Nullable<int> TOTAL_WORDS_RIGTH
		{
			get
			{
				return this._TOTAL_WORDS_RIGTH;
			}
			set
			{
				if ((this._TOTAL_WORDS_RIGTH != value))
				{
					this.OnTOTAL_WORDS_RIGTHChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_WORDS_RIGTH = value;
					this.SendPropertyChanged("TOTAL_WORDS_RIGTH");
					this.OnTOTAL_WORDS_RIGTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCamposContextuales_CamaraComercio_tbPalabrasClaves_CamaraComercio", Storage="_tbPalabrasClaves_CamaraComercio", ThisKey="CONSECUTIVO", OtherKey="FIELD_CONTEXTUAL")]
		public EntitySet<tbPalabrasClaves_CamaraComercio> tbPalabrasClaves_CamaraComercio
		{
			get
			{
				return this._tbPalabrasClaves_CamaraComercio;
			}
			set
			{
				this._tbPalabrasClaves_CamaraComercio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPalabrasClaves_CamaraComercio(tbPalabrasClaves_CamaraComercio entity)
		{
			this.SendPropertyChanging();
			entity.tbCamposContextuales_CamaraComercio = this;
		}
		
		private void detach_tbPalabrasClaves_CamaraComercio(tbPalabrasClaves_CamaraComercio entity)
		{
			this.SendPropertyChanging();
			entity.tbCamposContextuales_CamaraComercio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbEncabezados_CamaraComercio")]
	public partial class tbEncabezados_CamaraComercio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONSECUTIVO;
		
		private string _DESCRIPCION;
		
		private string _CIUDAD;
		
		private int _TIPO_MARGEN;
		
		private System.Nullable<int> _orden;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONSECUTIVOChanging(int value);
    partial void OnCONSECUTIVOChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnTIPO_MARGENChanging(int value);
    partial void OnTIPO_MARGENChanged();
    partial void OnordenChanging(System.Nullable<int> value);
    partial void OnordenChanged();
    #endregion
		
		public tbEncabezados_CamaraComercio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this.OnCONSECUTIVOChanging(value);
					this.SendPropertyChanging();
					this._CONSECUTIVO = value;
					this.SendPropertyChanged("CONSECUTIVO");
					this.OnCONSECUTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(4000)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="VarChar(200)")]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_MARGEN", DbType="Int NOT NULL")]
		public int TIPO_MARGEN
		{
			get
			{
				return this._TIPO_MARGEN;
			}
			set
			{
				if ((this._TIPO_MARGEN != value))
				{
					this.OnTIPO_MARGENChanging(value);
					this.SendPropertyChanging();
					this._TIPO_MARGEN = value;
					this.SendPropertyChanged("TIPO_MARGEN");
					this.OnTIPO_MARGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orden", DbType="Int")]
		public System.Nullable<int> orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				if ((this._orden != value))
				{
					this.OnordenChanging(value);
					this.SendPropertyChanging();
					this._orden = value;
					this.SendPropertyChanged("orden");
					this.OnordenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPalabrasClaves_CamaraComercio")]
	public partial class tbPalabrasClaves_CamaraComercio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONSECUTIVO;
		
		private string _KEY_WORD;
		
		private System.Nullable<int> _FIELD_CONTEXTUAL;
		
		private EntityRef<tbCamposContextuales_CamaraComercio> _tbCamposContextuales_CamaraComercio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONSECUTIVOChanging(int value);
    partial void OnCONSECUTIVOChanged();
    partial void OnKEY_WORDChanging(string value);
    partial void OnKEY_WORDChanged();
    partial void OnFIELD_CONTEXTUALChanging(System.Nullable<int> value);
    partial void OnFIELD_CONTEXTUALChanged();
    #endregion
		
		public tbPalabrasClaves_CamaraComercio()
		{
			this._tbCamposContextuales_CamaraComercio = default(EntityRef<tbCamposContextuales_CamaraComercio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this.OnCONSECUTIVOChanging(value);
					this.SendPropertyChanging();
					this._CONSECUTIVO = value;
					this.SendPropertyChanged("CONSECUTIVO");
					this.OnCONSECUTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_WORD", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string KEY_WORD
		{
			get
			{
				return this._KEY_WORD;
			}
			set
			{
				if ((this._KEY_WORD != value))
				{
					this.OnKEY_WORDChanging(value);
					this.SendPropertyChanging();
					this._KEY_WORD = value;
					this.SendPropertyChanged("KEY_WORD");
					this.OnKEY_WORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD_CONTEXTUAL", DbType="Int")]
		public System.Nullable<int> FIELD_CONTEXTUAL
		{
			get
			{
				return this._FIELD_CONTEXTUAL;
			}
			set
			{
				if ((this._FIELD_CONTEXTUAL != value))
				{
					if (this._tbCamposContextuales_CamaraComercio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFIELD_CONTEXTUALChanging(value);
					this.SendPropertyChanging();
					this._FIELD_CONTEXTUAL = value;
					this.SendPropertyChanged("FIELD_CONTEXTUAL");
					this.OnFIELD_CONTEXTUALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCamposContextuales_CamaraComercio_tbPalabrasClaves_CamaraComercio", Storage="_tbCamposContextuales_CamaraComercio", ThisKey="FIELD_CONTEXTUAL", OtherKey="CONSECUTIVO", IsForeignKey=true)]
		public tbCamposContextuales_CamaraComercio tbCamposContextuales_CamaraComercio
		{
			get
			{
				return this._tbCamposContextuales_CamaraComercio.Entity;
			}
			set
			{
				tbCamposContextuales_CamaraComercio previousValue = this._tbCamposContextuales_CamaraComercio.Entity;
				if (((previousValue != value) 
							|| (this._tbCamposContextuales_CamaraComercio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCamposContextuales_CamaraComercio.Entity = null;
						previousValue.tbPalabrasClaves_CamaraComercio.Remove(this);
					}
					this._tbCamposContextuales_CamaraComercio.Entity = value;
					if ((value != null))
					{
						value.tbPalabrasClaves_CamaraComercio.Add(this);
						this._FIELD_CONTEXTUAL = value.CONSECUTIVO;
					}
					else
					{
						this._FIELD_CONTEXTUAL = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbCamposContextuales_CamaraComercio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbParametros")]
	public partial class tbParametros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CONSECUTIVO;
		
		private string _NOMBRE_PARAMETRO;
		
		private string _VALOR;
		
		private System.Nullable<System.DateTime> _FECHA_CREACION;
		
		private System.Nullable<System.DateTime> _FECHA_ULTIMA_MODIFICACION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONSECUTIVOChanging(int value);
    partial void OnCONSECUTIVOChanged();
    partial void OnNOMBRE_PARAMETROChanging(string value);
    partial void OnNOMBRE_PARAMETROChanged();
    partial void OnVALORChanging(string value);
    partial void OnVALORChanged();
    partial void OnFECHA_CREACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_CREACIONChanged();
    partial void OnFECHA_ULTIMA_MODIFICACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_ULTIMA_MODIFICACIONChanged();
    #endregion
		
		public tbParametros()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this.OnCONSECUTIVOChanging(value);
					this.SendPropertyChanging();
					this._CONSECUTIVO = value;
					this.SendPropertyChanged("CONSECUTIVO");
					this.OnCONSECUTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PARAMETRO", DbType="VarChar(50)")]
		public string NOMBRE_PARAMETRO
		{
			get
			{
				return this._NOMBRE_PARAMETRO;
			}
			set
			{
				if ((this._NOMBRE_PARAMETRO != value))
				{
					this.OnNOMBRE_PARAMETROChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PARAMETRO = value;
					this.SendPropertyChanged("NOMBRE_PARAMETRO");
					this.OnNOMBRE_PARAMETROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="VarChar(200)")]
		public string VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this.OnVALORChanging(value);
					this.SendPropertyChanging();
					this._VALOR = value;
					this.SendPropertyChanged("VALOR");
					this.OnVALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_CREACION
		{
			get
			{
				return this._FECHA_CREACION;
			}
			set
			{
				if ((this._FECHA_CREACION != value))
				{
					this.OnFECHA_CREACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREACION = value;
					this.SendPropertyChanged("FECHA_CREACION");
					this.OnFECHA_CREACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ULTIMA_MODIFICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ULTIMA_MODIFICACION
		{
			get
			{
				return this._FECHA_ULTIMA_MODIFICACION;
			}
			set
			{
				if ((this._FECHA_ULTIMA_MODIFICACION != value))
				{
					this.OnFECHA_ULTIMA_MODIFICACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ULTIMA_MODIFICACION = value;
					this.SendPropertyChanged("FECHA_ULTIMA_MODIFICACION");
					this.OnFECHA_ULTIMA_MODIFICACIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSedes_CamaraComercio")]
	public partial class tbSedes_CamaraComercio
	{
		
		private int _CONSECUTIVO;
		
		private string _NOMBRE;
		
		private string _CAPTURE_CITY;
		
		public tbSedes_CamaraComercio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this._CONSECUTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPTURE_CITY", DbType="VarChar(50)")]
		public string CAPTURE_CITY
		{
			get
			{
				return this._CAPTURE_CITY;
			}
			set
			{
				if ((this._CAPTURE_CITY != value))
				{
					this._CAPTURE_CITY = value;
				}
			}
		}
	}
	
	public partial class spConsultarEncabezados_CamaraComercioResult
	{
		
		private string _DESCRIPCION;
		
		public spConsultarEncabezados_CamaraComercioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(4000)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class spConsultarLista_CamaraComercioResult
	{
		
		private int _CONSECUTIVO;
		
		private string _NOMBRE;
		
		private string _CAPTURE_CITY;
		
		public spConsultarLista_CamaraComercioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", DbType="Int NOT NULL")]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this._CONSECUTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPTURE_CITY", DbType="VarChar(50)")]
		public string CAPTURE_CITY
		{
			get
			{
				return this._CAPTURE_CITY;
			}
			set
			{
				if ((this._CAPTURE_CITY != value))
				{
					this._CAPTURE_CITY = value;
				}
			}
		}
	}
	
	public partial class spConsultarRegion_CamaraComercioResult
	{
		
		private string _NOMBRE;
		
		public spConsultarRegion_CamaraComercioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
	}
	
	public partial class spConsultarCamposContextuales_CamaraComercioResult
	{
		
		private int _CONSECUTIVO;
		
		private string _FIELD;
		
		private System.Nullable<int> _TOTAL_WORDS_LEFT;
		
		private System.Nullable<int> _TOTAL_WORDS_RIGTH;
		
		private System.Nullable<int> _ORDER_BY;
		
		public spConsultarCamposContextuales_CamaraComercioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", DbType="Int NOT NULL")]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this._CONSECUTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIELD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FIELD
		{
			get
			{
				return this._FIELD;
			}
			set
			{
				if ((this._FIELD != value))
				{
					this._FIELD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_WORDS_LEFT", DbType="Int")]
		public System.Nullable<int> TOTAL_WORDS_LEFT
		{
			get
			{
				return this._TOTAL_WORDS_LEFT;
			}
			set
			{
				if ((this._TOTAL_WORDS_LEFT != value))
				{
					this._TOTAL_WORDS_LEFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_WORDS_RIGTH", DbType="Int")]
		public System.Nullable<int> TOTAL_WORDS_RIGTH
		{
			get
			{
				return this._TOTAL_WORDS_RIGTH;
			}
			set
			{
				if ((this._TOTAL_WORDS_RIGTH != value))
				{
					this._TOTAL_WORDS_RIGTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_BY", DbType="Int")]
		public System.Nullable<int> ORDER_BY
		{
			get
			{
				return this._ORDER_BY;
			}
			set
			{
				if ((this._ORDER_BY != value))
				{
					this._ORDER_BY = value;
				}
			}
		}
	}
	
	public partial class spConsultarPalabrasClaves_CamaraComercioResult
	{
		
		private int _CONSECUTIVO;
		
		private string _KEY_WORD;
		
		public spConsultarPalabrasClaves_CamaraComercioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSECUTIVO", DbType="Int NOT NULL")]
		public int CONSECUTIVO
		{
			get
			{
				return this._CONSECUTIVO;
			}
			set
			{
				if ((this._CONSECUTIVO != value))
				{
					this._CONSECUTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_WORD", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string KEY_WORD
		{
			get
			{
				return this._KEY_WORD;
			}
			set
			{
				if ((this._KEY_WORD != value))
				{
					this._KEY_WORD = value;
				}
			}
		}
	}
	
	public partial class spConsultarEncabezadosGeneral_CamaraComercioResult
	{
		
		private string _CIUDAD;
		
		private string _DESCRIPCION;
		
		public spConsultarEncabezadosGeneral_CamaraComercioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="VarChar(200)")]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this._CIUDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(4000)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
